(* This file is part of the Catala build system, a specification language for
   tax and social benefits computation rules. Copyright (C) 2020 Inria,
   contributor: Emile Rolley <emile.rolley@tuta.io>

   Licensed under the Apache License, Version 2.0 (the "License"); you may not
   use this file except in compliance with the License. You may obtain a copy of
   the License at

   http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
   License for the specific language governing permissions and limitations under
   the License. *)

(** This library contains the implementations of utility functions used to
    generate {{:https://ninja-build.org} Ninja} build files in OCaml with almost
    no dependencies -- it only depends on
    {{:https://v3.ocaml.org/p/re/1.10.3/doc/Re/index.html} Re}. It's currently
    developed to be used by
    {{:https://github.com/CatalaLang/catala/tree/master/build_system} Clerk},
    the {{:https://catala-lang.org} Catala} build system. Therefore, the library
    {b supports only very basic features} required by Clerk. *)

(** {2 What is Ninja?} *)

(** {{:https://ninja-build.org} Ninja} is a low-level build system. It's
    designed to have its input files ({i build.ninja}) generated by a
    higher-level build system, and to run builds as fast as possible by
    supporting native cross-platform (Windows and Unix) parallel builds.

    See the {{:https://ninja-build.org/manual.html} manual} for more details. *)

(** {1 Ninja expressions} *)

(** Helper module to build ninja expressions. *)
module rec Expr : sig
  type elt =
    | Word of string
    (* one shell word, may embed scalar refs; always quoted in commands,
       $-escaped unquoted in paths *)
    | Splice of t Var.t
    | Raw of string
    (* never quoted: shell operators, ninja builtin refs (${in}); no spaces *)

  and t = elt list
  (** A ninja expression is a list of elements: [Word]s (single shell words,
      quoted as needed at emission), [Splice]s (references to vector
      variables), and [Raw] tokens (emitted as-is: shell operators, ninja
      builtin references). How each element is dressed depends on the position
      (command, path, description) where the expression is emitted; emission
      is internal to this library. *)
end

(** Ninja variable names, distinguishing binding name ("x") from references in
    expressions ("$x") *)
and Var : sig
  type 'a t = Scalar : string -> string t | Vector : string -> Expr.t t
  (** A [Scalar] holds a string: referenced with {!ref}, embeddable inside
      any [Word] or path. A [Vector] holds an {!Expr.t}: referenced only
      whole, with [Splice], in commands. *)

  type scalar = string t
  type vector = Expr.t t

  val make_scalar : string -> scalar
  val make_vector : string -> vector

  val name : 'a t -> string
  (** Var base name, used when binding it *)

  val ref : string t -> string
  (** Var reference with a preceding "$", for use in strings *)
end

(** Rule- or build-scoped [name = value] lines, for the [~vars] arguments *)
module Binding : sig
  type 'a t = 'a Var.t * 'a
  type any = Any : 'a t -> any

  val make : 'a Var.t -> 'a -> any
end

(** {1 Ninja statements} *)

(** Helper module to build
    {{:https://ninja-build.org/manual.html#_rules} ninja rules}. *)
module Rule : sig
  type t
  (** Represents the minimal ninja rule representation for Clerk:

      {[
        rule <name>
          command = <command>
          [description = <description>]
      ]} *)

  val make :
    ?vars:Binding.any list -> ?description:Expr.t -> string -> command:Expr.t -> t
  (** [make name ~command] returns the corresponding ninja {!type:Rule.t}. *)

  val format : Format.formatter -> t -> unit
  (** [format fmt rule] outputs in [fmt] the string representation of the ninja
      [rule]. *)
end

(** Helper module to build ninja
    {{:https://ninja-build.org/manual.html#_build_statements} build statements}. *)
module Build : sig
  type t
  (** Represents the minimal ninja build statement representation for Clerk:

      {[
        build <outputs>: <rule> [<inputs>]
          [<vars>]
      ]}*)

  val make :
    ?inputs:Expr.t ->
    ?implicit_in:Expr.t ->
    outputs:Expr.t ->
    ?implicit_out:Expr.t ->
    ?vars:Binding.any list ->
    string ->
    t
  (** [make ~outputs rule] returns the corresponding ninja {!type:Build.t}. *)

  val format : Format.formatter -> t -> unit
  (** [format fmt build] outputs in [fmt] the string representation of the ninja
      [build]. *)
end

module Default : sig
  type t

  val make : Expr.t -> t
  val format : Format.formatter -> t -> unit
end

type def
(** A ninja statement: comment, global binding, rule, build or default *)

val comment : string -> def
val binding : Binding.any -> def

val rule :
  ?vars:Binding.any list ->
  ?description:Expr.t ->
  string ->
  command:Expr.t ->
  def

val build :
  ?inputs:Expr.t ->
  ?implicit_in:Expr.t ->
  outputs:Expr.t ->
  ?implicit_out:Expr.t ->
  ?vars:Binding.any list ->
  string ->
  def

val default : Expr.t -> def
val format_def : Format.formatter -> def -> unit

type ninja = def Seq.t

val format : Format.formatter -> ninja -> unit
